// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "individual_types.h"
#include <Rcpp.h>

using namespace Rcpp;

// create_state
Rcpp::XPtr<State> create_state(const Rcpp::List individuals);
RcppExport SEXP _individual_create_state(SEXP individualsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type individuals(individualsSEXP);
    rcpp_result_gen = Rcpp::wrap(create_state(individuals));
    return rcpp_result_gen;
END_RCPP
}
// state_apply_updates
void state_apply_updates(Rcpp::XPtr<State> state);
RcppExport SEXP _individual_state_apply_updates(SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<State> >::type state(stateSEXP);
    state_apply_updates(state);
    return R_NilValue;
END_RCPP
}
// create_process_api
Rcpp::XPtr<ProcessAPI> create_process_api(Rcpp::XPtr<State> state, Rcpp::Environment scheduler, Rcpp::List params);
RcppExport SEXP _individual_create_process_api(SEXP stateSEXP, SEXP schedulerSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<State> >::type state(stateSEXP);
    Rcpp::traits::input_parameter< Rcpp::Environment >::type scheduler(schedulerSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(create_process_api(state, scheduler, params));
    return rcpp_result_gen;
END_RCPP
}
// process_get_state
std::vector<size_t> process_get_state(Rcpp::XPtr<ProcessAPI> api, const std::string individual, const std::vector<std::string> states);
RcppExport SEXP _individual_process_get_state(SEXP apiSEXP, SEXP individualSEXP, SEXP statesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<ProcessAPI> >::type api(apiSEXP);
    Rcpp::traits::input_parameter< const std::string >::type individual(individualSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string> >::type states(statesSEXP);
    rcpp_result_gen = Rcpp::wrap(process_get_state(api, individual, states));
    return rcpp_result_gen;
END_RCPP
}
// process_get_variable
std::vector<double> process_get_variable(Rcpp::XPtr<ProcessAPI> api, const std::string individual, const std::string variable);
RcppExport SEXP _individual_process_get_variable(SEXP apiSEXP, SEXP individualSEXP, SEXP variableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<ProcessAPI> >::type api(apiSEXP);
    Rcpp::traits::input_parameter< const std::string >::type individual(individualSEXP);
    Rcpp::traits::input_parameter< const std::string >::type variable(variableSEXP);
    rcpp_result_gen = Rcpp::wrap(process_get_variable(api, individual, variable));
    return rcpp_result_gen;
END_RCPP
}
// process_queue_state_update
void process_queue_state_update(Rcpp::XPtr<ProcessAPI> api, const std::string individual, const std::string state, const std::vector<size_t> index_vector);
RcppExport SEXP _individual_process_queue_state_update(SEXP apiSEXP, SEXP individualSEXP, SEXP stateSEXP, SEXP index_vectorSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<ProcessAPI> >::type api(apiSEXP);
    Rcpp::traits::input_parameter< const std::string >::type individual(individualSEXP);
    Rcpp::traits::input_parameter< const std::string >::type state(stateSEXP);
    Rcpp::traits::input_parameter< const std::vector<size_t> >::type index_vector(index_vectorSEXP);
    process_queue_state_update(api, individual, state, index_vector);
    return R_NilValue;
END_RCPP
}
// process_queue_variable_update
void process_queue_variable_update(Rcpp::XPtr<ProcessAPI> api, const std::string individual, const std::string variable, const std::vector<size_t> index, const std::vector<double> values);
RcppExport SEXP _individual_process_queue_variable_update(SEXP apiSEXP, SEXP individualSEXP, SEXP variableSEXP, SEXP indexSEXP, SEXP valuesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<ProcessAPI> >::type api(apiSEXP);
    Rcpp::traits::input_parameter< const std::string >::type individual(individualSEXP);
    Rcpp::traits::input_parameter< const std::string >::type variable(variableSEXP);
    Rcpp::traits::input_parameter< const std::vector<size_t> >::type index(indexSEXP);
    Rcpp::traits::input_parameter< const std::vector<double> >::type values(valuesSEXP);
    process_queue_variable_update(api, individual, variable, index, values);
    return R_NilValue;
END_RCPP
}
// execute_process
void execute_process(Rcpp::XPtr<process_t> process, Rcpp::XPtr<ProcessAPI> api);
RcppExport SEXP _individual_execute_process(SEXP processSEXP, SEXP apiSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<process_t> >::type process(processSEXP);
    Rcpp::traits::input_parameter< Rcpp::XPtr<ProcessAPI> >::type api(apiSEXP);
    execute_process(process, api);
    return R_NilValue;
END_RCPP
}
// execute_listener
void execute_listener(Rcpp::XPtr<listener_t> listener, Rcpp::XPtr<ProcessAPI> api, std::vector<size_t> target);
RcppExport SEXP _individual_execute_listener(SEXP listenerSEXP, SEXP apiSEXP, SEXP targetSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::XPtr<listener_t> >::type listener(listenerSEXP);
    Rcpp::traits::input_parameter< Rcpp::XPtr<ProcessAPI> >::type api(apiSEXP);
    Rcpp::traits::input_parameter< std::vector<size_t> >::type target(targetSEXP);
    execute_listener(listener, api, target);
    return R_NilValue;
END_RCPP
}
// fixed_probability_state_change_process
Rcpp::XPtr<process_t> fixed_probability_state_change_process(const std::string individual, const std::string state_from, const std::string state_to, double rate);
RcppExport SEXP _individual_fixed_probability_state_change_process(SEXP individualSEXP, SEXP state_fromSEXP, SEXP state_toSEXP, SEXP rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string >::type individual(individualSEXP);
    Rcpp::traits::input_parameter< const std::string >::type state_from(state_fromSEXP);
    Rcpp::traits::input_parameter< const std::string >::type state_to(state_toSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    rcpp_result_gen = Rcpp::wrap(fixed_probability_state_change_process(individual, state_from, state_to, rate));
    return rcpp_result_gen;
END_RCPP
}
// update_state_listener
Rcpp::XPtr<listener_t> update_state_listener(const std::string individual, const std::string state);
RcppExport SEXP _individual_update_state_listener(SEXP individualSEXP, SEXP stateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string >::type individual(individualSEXP);
    Rcpp::traits::input_parameter< const std::string >::type state(stateSEXP);
    rcpp_result_gen = Rcpp::wrap(update_state_listener(individual, state));
    return rcpp_result_gen;
END_RCPP
}
// reschedule_listener
Rcpp::XPtr<listener_t> reschedule_listener(const std::string event, double delay);
RcppExport SEXP _individual_reschedule_listener(SEXP eventSEXP, SEXP delaySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string >::type event(eventSEXP);
    Rcpp::traits::input_parameter< double >::type delay(delaySEXP);
    rcpp_result_gen = Rcpp::wrap(reschedule_listener(event, delay));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP run_testthat_tests();

static const R_CallMethodDef CallEntries[] = {
    {"_individual_create_state", (DL_FUNC) &_individual_create_state, 1},
    {"_individual_state_apply_updates", (DL_FUNC) &_individual_state_apply_updates, 1},
    {"_individual_create_process_api", (DL_FUNC) &_individual_create_process_api, 3},
    {"_individual_process_get_state", (DL_FUNC) &_individual_process_get_state, 3},
    {"_individual_process_get_variable", (DL_FUNC) &_individual_process_get_variable, 3},
    {"_individual_process_queue_state_update", (DL_FUNC) &_individual_process_queue_state_update, 4},
    {"_individual_process_queue_variable_update", (DL_FUNC) &_individual_process_queue_variable_update, 5},
    {"_individual_execute_process", (DL_FUNC) &_individual_execute_process, 2},
    {"_individual_execute_listener", (DL_FUNC) &_individual_execute_listener, 3},
    {"_individual_fixed_probability_state_change_process", (DL_FUNC) &_individual_fixed_probability_state_change_process, 4},
    {"_individual_update_state_listener", (DL_FUNC) &_individual_update_state_listener, 2},
    {"_individual_reschedule_listener", (DL_FUNC) &_individual_reschedule_listener, 2},
    {"run_testthat_tests", (DL_FUNC) &run_testthat_tests, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_individual(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
