# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_bitset <- function(size) {
    .Call(`_individual_create_bitset`, size)
}

bitset_copy <- function(b) {
    .Call(`_individual_bitset_copy`, b)
}

bitset_insert <- function(b, v) {
    invisible(.Call(`_individual_bitset_insert`, b, v))
}

bitset_remove <- function(b, v) {
    invisible(.Call(`_individual_bitset_remove`, b, v))
}

bitset_size <- function(b) {
    .Call(`_individual_bitset_size`, b)
}

bitset_max_size <- function(b) {
    .Call(`_individual_bitset_max_size`, b)
}

bitset_and <- function(a, b) {
    invisible(.Call(`_individual_bitset_and`, a, b))
}

bitset_not <- function(b) {
    .Call(`_individual_bitset_not`, b)
}

bitset_or <- function(a, b) {
    invisible(.Call(`_individual_bitset_or`, a, b))
}

bitset_sample <- function(b, rate) {
    invisible(.Call(`_individual_bitset_sample`, b, rate))
}

bitset_to_vector <- function(b) {
    .Call(`_individual_bitset_to_vector`, b)
}

create_event <- function() {
    .Call(`_individual_create_event`)
}

create_targeted_event <- function(size) {
    .Call(`_individual_create_targeted_event`, size)
}

event_tick <- function(event) {
    invisible(.Call(`_individual_event_tick`, event))
}

event_schedule <- function(event, delays) {
    invisible(.Call(`_individual_event_schedule`, event, delays))
}

event_clear_schedule <- function(event) {
    invisible(.Call(`_individual_event_clear_schedule`, event))
}

targeted_event_clear_schedule_vector <- function(event, target) {
    invisible(.Call(`_individual_targeted_event_clear_schedule_vector`, event, target))
}

targeted_event_clear_schedule <- function(event, target) {
    invisible(.Call(`_individual_targeted_event_clear_schedule`, event, target))
}

event_get_scheduled <- function(event) {
    .Call(`_individual_event_get_scheduled`, event)
}

targeted_event_schedule <- function(event, target, delay) {
    invisible(.Call(`_individual_targeted_event_schedule`, event, target, delay))
}

targeted_event_schedule_vector <- function(event, target, delay) {
    invisible(.Call(`_individual_targeted_event_schedule_vector`, event, target, delay))
}

targeted_event_schedule_multi_delay <- function(event, target, delay) {
    invisible(.Call(`_individual_targeted_event_schedule_multi_delay`, event, target, delay))
}

event_get_timestep <- function(event) {
    .Call(`_individual_event_get_timestep`, event)
}

event_should_trigger <- function(event) {
    .Call(`_individual_event_should_trigger`, event)
}

event_get_target <- function(event) {
    .Call(`_individual_event_get_target`, event)
}

execute_process <- function(process, timestep) {
    invisible(.Call(`_individual_execute_process`, process, timestep))
}

create_categorical_variable <- function(categories, values) {
    .Call(`_individual_create_categorical_variable`, categories, values)
}

categorical_variable_queue_update <- function(variable, value, index) {
    invisible(.Call(`_individual_categorical_variable_queue_update`, variable, value, index))
}

categorical_variable_get_index_of <- function(variable, values) {
    .Call(`_individual_categorical_variable_get_index_of`, variable, values)
}

categorical_variable_queue_update_vector <- function(variable, value, index) {
    invisible(.Call(`_individual_categorical_variable_queue_update_vector`, variable, value, index))
}

categorical_variable_update <- function(variable) {
    invisible(.Call(`_individual_categorical_variable_update`, variable))
}

create_double_variable <- function(values) {
    .Call(`_individual_create_double_variable`, values)
}

double_variable_get_values <- function(variable) {
    .Call(`_individual_double_variable_get_values`, variable)
}

double_variable_get_values_at_index <- function(variable, index) {
    .Call(`_individual_double_variable_get_values_at_index`, variable, index)
}

double_variable_get_values_at_index_vector <- function(variable, index) {
    .Call(`_individual_double_variable_get_values_at_index_vector`, variable, index)
}

double_variable_queue_fill <- function(variable, value) {
    invisible(.Call(`_individual_double_variable_queue_fill`, variable, value))
}

double_variable_queue_update <- function(variable, value, index) {
    invisible(.Call(`_individual_double_variable_queue_update`, variable, value, index))
}

double_variable_update <- function(variable) {
    invisible(.Call(`_individual_double_variable_update`, variable))
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_individual_RcppExport_registerCCallable', PACKAGE = 'individual')
})
