# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@title create a listener to update the state of the target population
#'@param individual the name of the individual type
#'@param state the state to transition to
#'@export
update_state_listener <- function(individual, state) {
    .Call(`_individual_update_state_listener`, individual, state)
}

#'@title create a listener to schedule a target population for a new event
#'@param event the name of the event to schedule
#'@param delay the delay for the new event
#'@export
reschedule_listener <- function(event, delay) {
    .Call(`_individual_reschedule_listener`, event, delay)
}

#'@title create a process to transition individuals between states at a constant rate
#'@param individual the name of an individual
#'@param from_state the name of the source state
#'@param to_state the name of the target state
#'@param rate the rate at which state transitions occur
#'@export
fixed_probability_state_change_process <- function(individual, from_state, to_state, rate) {
    .Call(`_individual_fixed_probability_state_change_process`, individual, from_state, to_state, rate)
}

#'@title create a process to render the number of individuals in the specified states
#'@param individual the name of an individual
#'@param states a vector of state names
#'@export
state_count_renderer_process <- function(individual, states) {
    .Call(`_individual_state_count_renderer_process`, individual, states)
}

#'@title create a process to render the mean value of the specified variables
#'@param individual the name of an individual
#'@param variables a vector of variable names
#'@export
variable_mean_renderer_process <- function(individual, variables) {
    .Call(`_individual_variable_mean_renderer_process`, individual, variables)
}

execute_process <- function(process, api) {
    invisible(.Call(`_individual_execute_process`, process, api))
}

create_process_api <- function(state, scheduler, params, renderer) {
    .Call(`_individual_create_process_api`, state, scheduler, params, renderer)
}

process_get_state <- function(api, individual, states) {
    .Call(`_individual_process_get_state`, api, individual, states)
}

process_get_variable <- function(api, individual, variable) {
    .Call(`_individual_process_get_variable`, api, individual, variable)
}

process_get_variable_at_index <- function(api, individual, variable, index) {
    .Call(`_individual_process_get_variable_at_index`, api, individual, variable, index)
}

process_queue_state_update <- function(api, individual, state, index_vector) {
    invisible(.Call(`_individual_process_queue_state_update`, api, individual, state, index_vector))
}

process_queue_variable_update <- function(api, individual, variable, index, values) {
    invisible(.Call(`_individual_process_queue_variable_update`, api, individual, variable, index, values))
}

process_queue_variable_fill <- function(api, individual, variable, value) {
    invisible(.Call(`_individual_process_queue_variable_fill`, api, individual, variable, value))
}

process_schedule <- function(api, event, index_vector, delay) {
    invisible(.Call(`_individual_process_schedule`, api, event, index_vector, delay))
}

process_get_scheduled <- function(api, event) {
    .Call(`_individual_process_get_scheduled`, api, event)
}

process_clear_schedule <- function(api, event, index) {
    invisible(.Call(`_individual_process_clear_schedule`, api, event, index))
}

process_get_timestep <- function(api) {
    .Call(`_individual_process_get_timestep`, api)
}

create_scheduler <- function(individuals) {
    .Call(`_individual_create_scheduler`, individuals)
}

scheduler_tick <- function(scheduler) {
    invisible(.Call(`_individual_scheduler_tick`, scheduler))
}

scheduler_process_events <- function(scheduler, cpp_api, r_api) {
    invisible(.Call(`_individual_scheduler_process_events`, scheduler, cpp_api, r_api))
}

create_cpp_state <- function(individuals, population_sizes) {
    .Call(`_individual_create_cpp_state`, individuals, population_sizes)
}

state_add_states <- function(state, individual, state_names, initial_sizes) {
    invisible(.Call(`_individual_state_add_states`, state, individual, state_names, initial_sizes))
}

state_add_variable <- function(state, individual, variable, initial) {
    invisible(.Call(`_individual_state_add_variable`, state, individual, variable, initial))
}

state_apply_updates <- function(state) {
    invisible(.Call(`_individual_state_apply_updates`, state))
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_individual_RcppExport_registerCCallable', PACKAGE = 'individual')
})
