# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@export
update_state_listener <- function(individual, state) {
    .Call(`_individual_update_state_listener`, individual, state)
}

#'@export
reschedule_listener <- function(event, delay) {
    .Call(`_individual_reschedule_listener`, event, delay)
}

#'@export
fixed_probability_state_change_process <- function(individual, from_state, to_state, rate) {
    .Call(`_individual_fixed_probability_state_change_process`, individual, from_state, to_state, rate)
}

#'@export
state_count_renderer_process <- function(individual, states) {
    .Call(`_individual_state_count_renderer_process`, individual, states)
}

#'@export
variable_mean_renderer_process <- function(individual, variables) {
    .Call(`_individual_variable_mean_renderer_process`, individual, variables)
}

execute_process <- function(process, api) {
    invisible(.Call(`_individual_execute_process`, process, api))
}

create_process_api <- function(state, scheduler, params, renderer) {
    .Call(`_individual_create_process_api`, state, scheduler, params, renderer)
}

process_get_state <- function(api, individual, states) {
    .Call(`_individual_process_get_state`, api, individual, states)
}

process_get_variable <- function(api, individual, variable) {
    .Call(`_individual_process_get_variable`, api, individual, variable)
}

process_get_variable_at_index <- function(api, individual, variable, index) {
    .Call(`_individual_process_get_variable_at_index`, api, individual, variable, index)
}

process_queue_state_update <- function(api, individual, state, index_vector) {
    invisible(.Call(`_individual_process_queue_state_update`, api, individual, state, index_vector))
}

process_queue_variable_update <- function(api, individual, variable, index, values) {
    invisible(.Call(`_individual_process_queue_variable_update`, api, individual, variable, index, values))
}

process_schedule <- function(api, event, index_vector, delay) {
    invisible(.Call(`_individual_process_schedule`, api, event, index_vector, delay))
}

process_get_scheduled <- function(api, event) {
    .Call(`_individual_process_get_scheduled`, api, event)
}

process_clear_schedule <- function(api, event, index) {
    invisible(.Call(`_individual_process_clear_schedule`, api, event, index))
}

process_get_timestep <- function(api) {
    .Call(`_individual_process_get_timestep`, api)
}

create_scheduler <- function(events) {
    .Call(`_individual_create_scheduler`, events)
}

scheduler_tick <- function(scheduler) {
    invisible(.Call(`_individual_scheduler_tick`, scheduler))
}

scheduler_process_events <- function(scheduler, cpp_api, r_api) {
    invisible(.Call(`_individual_scheduler_process_events`, scheduler, cpp_api, r_api))
}

create_state <- function(individuals) {
    .Call(`_individual_create_state`, individuals)
}

state_apply_updates <- function(state) {
    invisible(.Call(`_individual_state_apply_updates`, state))
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_individual_RcppExport_registerCCallable', PACKAGE = 'individual')
})
